name: "Sync SubBranches"
author: "Girish V"
description: 'Automatically sync branches and notify users about merge conflicts or successes.'
branding:
  icon: "https://github.com/GirishCodeAlchemy/GirishCodeAlchemy/blob/48e9c133950e09d23ae5b11b0ee40d41add0a507/logo.jpg"
  color: 'blue'
runs:
  using: "docker"
  image: "Dockerfile"
inputs:
  smtp-username:
    description: 'SMTP username for sending email notifications.'
    required: true
  smtp-password:
    description: 'SMTP password for sending email notifications.'
    required: true

outputs:
  conflict:
    description: 'The branch with merge conflict, if any.'