name: "Sync SubBranches"
author: "Girish V"
description: 'Automatically sync branches and notify users about merge conflicts or successes.'
branding:
  icon: 'git-merge'
  color: 'gray-dark'
runs:
  using: "docker"
  image: "Dockerfile"
inputs:
  smtp-username:
    description: 'SMTP username for sending email notifications.'
    required: true
  smtp-password:
    description: 'SMTP password for sending email notifications.'
    required: true

outputs:
  conflict:
    description: 'The branch with merge conflict, if any.'